---
  ps_users:
    - { name: 'ichiban', pass: 'ichiV@gran7' }
    - { name: 'niban', pass: 'niV@gran7' }
    - { name: 'sanban', pass: 'sanV@gran7'}
    - { name: 'yonban', pass: 'yonV@gran7'}
  ps_fold_ls:
    - { from: 'Desktop', to: 'Desktop' }
    - { from: 'Documents', to: 'Documents' }
    - { from: 'Personal', to: 'Documents' }
    - { from: 'Personal', to: 'Documents' }
    - { from: 'Favorites', to: 'Favorites' }
    - { from: 'Music', to: 'Music' }
    - { from: 'My Music', to: 'Music' }
    - { from: 'Pictures', to: 'Pictures' }
    - { from: 'My Pictures', to: 'Pictures' }
    - { from: 'Video', to: 'Video' }
    - { from: 'My Video', to: 'Video' }
